### ISSUE TITLE
Quantile normalization onto target where the target is a different size than x

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [bmbolstad/preprocessCore#11]
I implemented a quantile normalization method for Python (https://github.com/Maarten-vd-Sande/qnorm), and got a question from @marcmaxson if my implementation could support target distributions that are longer than x (since your implementation also supports that). 

I've been digging through the source code but I haven't been able to find how that is implemented so I thought I would just ask you :). Could you point me to the relevant source code / explain me how preprocessCore works when target has a different length than x.

**Comment by bmbolstad** [comment]
You would want to look at the "using_target" function in src/qnorm.c

**Comment by Maarten-vd-Sande** [comment]
Seems like interpolation. Thanks :tada:
