### ISSUE TITLE
package ‘preprocessCore’ is not available (for R version 3.6.1)

### ISSUE THREAD

**Issue by Hocnonsense** [bmbolstad/preprocessCore#9]
R version 3.6.1
```
> install.packages("preprocessCore")
Warning in install.packages :
  package ‘preprocessCore’ is not available (for R version 3.6.1)
```

**Comment by bmbolstad** [comment]
preprocessCore is a Bioconductor distributed package.   I don’t think install.packages() installs Bioc packages.

**Comment by Hocnonsense** [comment]
Thanks! It dose work by running `BiocManager::install("preprocessCore")`!
